### ISSUE TITLE
Support for more REPL providers

### ISSUE THREAD

**Issue by GCBallesteros** [GCBallesteros/NotebookNavigator.nvim#2]
Notebook Navigator only supports `iron.nvim` but it would be nice if either REPL would work too.

**Comment by cnrrobertson** [comment]
Hi, I'd be very interested in this. I don't use language specific REPL plugins but just send text to a buffer specific [toggleterm](https://github.com/akinsho/toggleterm.nvim) that is running a repl in my language of choice. 

What kind of implementation did you have in mind? It seems that iron is really only used [here](https://github.com/GCBallesteros/NotebookNavigator.nvim/blob/b336dfd63161058604fa2c0cfaac89e64049ec81/lua/notebook-navigator/core.lua#L62). Maybe add a repl provider config option [here](https://github.com/GCBallesteros/NotebookNavigator.nvim/blob/b336dfd63161058604fa2c0cfaac89e64049ec81/lua/notebook-navigator/init.lua#L173) and then check which provider to use [here](https://github.com/GCBallesteros/NotebookNavigator.nvim/blob/b336dfd63161058604fa2c0cfaac89e64049ec81/lua/notebook-navigator/core.lua#L62) before sending?

**Comment by GCBallesteros** [comment]
Hi @cnrrobertson thanks for looking into this. I'd be happy to merge a PR adding support for `toggleterm.nvim` if you are interested on working on it.

Something like what you are suggesting sounds about right. More specifically, what I had in mind was following the pattern used by the `commenter` system. That would mean having a file called `repl.lua` that provided a function `send_code(lines, repl_provider)` where `repl_provider` is a new string value added to the configuration. This function would be called in place of `iron.send` in  `core.lua:run_cell` which would also need to take in the `repl_provider` argument.  The final touch would be to update `init.lua` with the new argument [here](https://github.com/GCBallesteros/NotebookNavigator.nvim/blob/b336dfd63161058604fa2c0cfaac89e64049ec81/lua/notebook-navigator/init.lua#L72).

I'm open to changing my mind about how this would work if you have a better idea of course.
