### ISSUE TITLE
Windows split horizontally instead of vertically

### ISSUE THREAD

**Issue by ChengAoShen** [GCBallesteros/NotebookNavigator.nvim#21]
Hi, thanks for your excellent plugins! I miss some problems when I use this, the windows split horizontally when I press `<leader>x`,  I believe some things are wrong. This is the screenshot of my neovim
![image](https://github.com/GCBallesteros/NotebookNavigator.nvim/assets/68673559/9bf7d908-607c-4ce9-a6f7-d92283b8bf90)
Have I made any mistakes in my configs?
<img width="1102" alt="image" src="https://github.com/GCBallesteros/NotebookNavigator.nvim/assets/68673559/f33899a4-ed8b-489a-9db2-71465dc2ed51">

**Comment by GCBallesteros** [comment]
Hi, thanks for the kind words :)

I see you are using [iron.nvim](https://github.com/Vigemus/iron.nvim) as your REPL provider. How the REPL opens is controlled not by the NotebookNavigator configuration but by the iron.nvim one; here is [how](https://github.com/Vigemus/iron.nvim#how-to-configure). There are many many options to adjust it exactly to your taste, have a look. I, in particular, prefer a vertical split, to achieve it I use the following config:

```lua
return {
  "hkupty/iron.nvim",
  config = function()
    local iron = require "iron.core"
    iron.setup({
      config = {
        scratch_repl = true,
        repl_definition = {
          python = {
            command = { "ipython" },
            format = require("iron.fts.common").bracketed_paste,
          },
        },
        repl_open_cmd = "vertical botright 80 split",
      },
    })
  end,
}
```

> [!NOTE]
> It has been almost 2 years since I don't touch my iron config so there may be more elegant or succint ways to achieve the same thing. For example, I see you have `ipython` open but the default behaviour of iron many moons ago was to open the regular Python repl.

**Comment by ChengAoShen** [comment]
Yeah, my Neovim and the plugin work well after I add your configs to my file. Maybe I will try to discover more details of iron features by myself. All in all, the plugin is working. Thanks again for your kind help.
