### ISSUE TITLE
Suggestion: Use double-percent comments as default cell markers

### ISSUE THREAD

**Issue by chrisgrieser** [GCBallesteros/NotebookNavigator.nvim#23]
Instead of defining cell markers manually for every language, one could use `:h commentstring` and fill in `%%` as a de facto standard (e.g. [outlined by jupytext](https://jupytext.readthedocs.io/en/latest/formats-scripts.html#the-percent-format)).

That simplify the plugin config, and also make cell markers available without the need for the user to set anything up. That way, the plugin could be used out of the box for most languages, e.g. when you want to work "notebook-style" with javascript

```lua
-- determine the cell marker for any language
cell_marker = vim.bo.commentstring:format("%%")
```

**Comment by GCBallesteros** [comment]
Having `%%` it as default behavior seems like a good  and practical idea. However, I will leave the ability to configure in a per language basis for backwards compatibility reasons. Are you interested on submitting a PR to implement this?
