### ISSUE TITLE
assets folder vs github hosted gif

### ISSUE THREAD

**Issue by benlubas** [GCBallesteros/NotebookNavigator.nvim#26]
Github can host media for your readme so that it doesn't have to live in the repo and be downloaded by everyone that uses the plugin. 

You can just drag and drop the file over the readme and it'll give you a media link

**Comment by GCBallesteros** [comment]
I knew about this but I liked the idea of having the repo truly self contained but not wanting to throw in large files into the repo is also stopping me from doing things that should be trivial like updating the gif which is badly out of date. 

Will do it in the future, however, I don't want to rewrite history by purging the gif so the one currently in place will stay there as a reminder for my future self.
