### ISSUE TITLE
info: `nvim-various-textobjs` also supports Notebook cells as text operators

### ISSUE THREAD

**Issue by chrisgrieser** [GCBallesteros/NotebookNavigator.nvim#29]
https://github.com/chrisgrieser/nvim-various-textobjs

in case you find it worth mentioning in the docs. (didn't want to do a PR where I simply add my own plugin, therefore just an issue here.)

**Comment by GCBallesteros** [comment]
Added a reference to your plugin on the README. Thanks for your contributions!
