### ISSUE TITLE
Getting error 'Cursor position outside buffer' when executing a cell

### ISSUE THREAD

**Issue by tabrez** [GCBallesteros/NotebookNavigator.nvim#30]
I'm using the current version of AstriNVim configuration with the following changes to the configuration:

```lua
return  {
  {
    "GCBallesteros/NotebookNavigator.nvim",
    keys = {
      { "]h", function() require("notebook-navigator").move_cell "d" end },
      { "[h", function() require("notebook-navigator").move_cell "u" end },
      { "<leader>X", "<cmd>lua require('notebook-navigator').run_cell()<cr>" },
      { "<leader>x", "<cmd>lua require('notebook-navigator').run_and_move()<cr>" },
    },
    dependencies = {
      "echasnovski/mini.comment",
      "hkupty/iron.nvim", -- repl provider
      -- "akinsho/toggleterm.nvim", -- alternative repl provider
      "anuvyklack/hydra.nvim",
    },
    event = "VeryLazy",
    config = function()
      local nn = require "notebook-navigator"
      nn.setup({ activate_hydra_keys = "<leader>h" })
    end,
  }
}
```

There are no other user changes. I'm able to move around code cells using "]h" and "[h" and am able to activate the hydra mode using "<space>h". But when I try to execute a code cell using "[space]x" or "[space]X" or "x",  or "X" in hydra mode, I get the following error:

```text
E5108: Error executing lua .../NotebookNavigator.nvim/lua/notebook-navigator/repls.lua:35: Cursor position outside
buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        .../NotebookNavigator.nvim/lua/notebook-navigator/repls.lua:35: in function 'repl'
        ...y/NotebookNavigator.nvim/lua/notebook-navigator/core.lua:105: in function 'run_cell'
        ...y/NotebookNavigator.nvim/lua/notebook-navigator/core.lua:109: in function 'run_and_move'
        ...y/NotebookNavigator.nvim/lua/notebook-navigator/init.lua:84: in function 'run_and_move'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

Everything other than "x" or "X" works in hydra mode. I'm using the following python code for testing:

```python
print('hello world')
# %%
print('goodbye')
print('let us go back')
# %%
print('hello again')
# %%
```

I start vim from a terminal where the desired python virtual environment is already activated.

**Comment by GCBallesteros** [comment]
Thanks for the bug report.

The first problem is that the plugin is trying to run with toggleterm which I assume you have installed. I have fixed this on a commit I just pushed. Can you update and rerun?  Also, please make sure that you have configured iron.nvim adequately. 

Please send over your iron and toggleterm configs.

Thanks!

**Comment by tabrez** [comment]
I'm not sure how to update an installed plugin to the latest commit. I have tried adding the following line to `NotebookNavigator` configuration as per `lazy.nvim` documentation but I'm not entirely sure this is how it's done:

`config = { defaults = { version = "*" } },`
Restarted the editor and tested running a cell like earlier, got the same error.
Then I tried the following line instead: `version = "*",`
Restarted the editor and tested running a cell like earlier, got the same error. By the way, I see that the latest commit in `main` branch in the repo is 3 days old.

I believe `toggleterm` is included in the installation of `AstroNVim` as I'm getting a floating terminal when I run `:ToggleTerm`. I have not done any configuration for it. 

My `iron.nvim` configuration(copy/pasted from the plugin's github page into my config):

```lua
{
    'Vigemus/iron.nvim',
    config = function()
      require("iron.core").setup {
        -- repl_open_cmd = "vertical botright 80 split",
        config = {
          repl_open_cmd = require('iron.view').split.vertical.botright("50%"),
          repl_definition = {
            sh = {
              -- Can be a table or a function that
              -- returns a table (see below)
              command = {"ipython"}
            }
          },
        },
        keymaps = {
          send_motion = "<space>sc",
          visual_send = "<space>sc",
          send_file = "<space>sf",
          send_line = "<space>sl",
          send_until_cursor = "<space>su",
          send_mark = "<space>sm",
          mark_motion = "<space>mc",
          mark_visual = "<space>mc",
          remove_mark = "<space>md",
          cr = "<space>s<cr>",
          interrupt = "<space>s<space>",
          exit = "<space>sq",
          clear = "<space>cl",
        }
      }
    end
  }
```

I'm able to run visually selected python code fine using `iron.nvim` keybinds like `<space>sc`. It opens a pane/window on the right side and executes the statements there in a python repl.

**Comment by GCBallesteros** [comment]
```lua
return {
   "author/repo",
   commit = "b504a109ce9c",
   -- .... more things
}
```

will pin the plugin to a specific commit. Now you wont get any updates at all. Since NotebookNavigator is not versioned you don't need to add anything to the lazy config. I would go back to the default config. To update with Lazy you can:

1. Run `:Lazy` this will open the lazy interface.
2. Press `U`. This is capital U, i.e `<shift>u`.

This will update every plugin. Please update your repos once more after unpinning NotebookNavigator. You should end up in commit: `6579ca1.....`

Finally, here is an iron config that is known to work.

```lua
return {
  "hkupty/iron.nvim",
  config = function()
    local iron = require "iron.core"
    iron.setup({
      config = {
        scratch_repl = true,
        repl_definition = {
          python = {
            command = { "ipython" },
            format = require("iron.fts.common").bracketed_paste,
          },
        },
        repl_open_cmd = "vertical botright 80 split",
      },
    })
  end,
}
```

**Comment by tabrez** [comment]
I can see the new commit now(6579ca1969327f311371c48fe85964ace68d542f) and using this version with the default config of `iron.nvim` and `notebook-navigator`, everything works perfectly. Thanks!
I have been looking for a Neovim plugin that allows me to execute code cells marked with delimiters like "# %%" in the same way VS Code/Atom/etc. support and am very thankful that you have implemented it in such a nice plugin.
