### ISSUE TITLE
Getting error 'IndentationError: unexpected indent' when executing a cell with an inner function containing a new line

### ISSUE THREAD

**Issue by tabrez** [GCBallesteros/NotebookNavigator.nvim#31]
I'm executing the following python code in a cell using the keybind `<space>x`:

```python
# %% helper utils
def time_function(func):
  def wrapper(*args, **kwargs):
    start = time.time()
    result = func(*args, **kwargs)
    elapsed_time = time.time() - start

    if elapsed_time < 60:
      print(f'Executed time: {elapsed_time:.2f} secs')
    else:
      print(f'Executed time: {elapsed_time / 60:.2f} mins')
    return result

  return wrapper
```

I'm getting the following error in the repl window:

```text
>>> def time_function(func):
...   def wrapper(*args, **kwargs):
...     start = time.time()
...     result = func(*args, **kwargs)
...     elapsed_time = time.time() - start
... 
>>>     if elapsed_time < 60:
  File "<stdin>", line 1
    if elapsed_time < 60:
IndentationError: unexpected indent
>>>       print(f'Executed time: {elapsed_time:.2f} secs')
  File "<stdin>", line 1
    print(f'Executed time: {elapsed_time:.2f} secs')
IndentationError: unexpected indent
>>>     else:
  File "<stdin>", line 1
    else:
IndentationError: unexpected indent
>>>       print(f'Executed time: {elapsed_time / 60:.2f} mins')
  File "<stdin>", line 1
    print(f'Executed time: {elapsed_time / 60:.2f} mins')
IndentationError: unexpected indent
>>>     return result
  File "<stdin>", line 1
    return result
IndentationError: unexpected indent
>>> 
>>>   return wrapper
  File "<stdin>", line 1
    return wrapper
IndentationError: unexpected indent
```

I'm getting similar error for another python cell with the following code:

```text
>>> def compute_metrics(eval_preds):
...   def postprocess_text(
...     preds: List[str], labels: List[str]
...   ) -> Tuple[List[str], List[List[str]]]:
...     new_preds: List[str] = [pred.strip() for pred in preds]
...     new_labels: List[List[str]] = [[label.strip()] for label in labels]
... 
>>>     return new_preds, new_labels
  File "<stdin>", line 1
    return new_preds, new_labels
IndentationError: unexpected indent
>>> 
>>>   preds, labels = eval_preds
  File "<stdin>", line 1
    preds, labels = eval_preds
IndentationError: unexpected indent
```

One common thing between the above two code blocks is that they contain an inner function and the inner function has an empty line where the indentation error is reported. All other python cells run without errors so far using `<space>x` keybind.

The code block runs fine in vscode, when using `iron.nvim` keybind `<space>sc` in neovim, and when copy/pasted into `ipython` repl in a terminal.

I tested with the following modified version by removing all empty lines and it runs without errors(I had to remove both new lines above and below if/else block):

```python
def time_function(func):
  def wrapper(*args, **kwargs):
    start = time.time()
    result = func(*args, **kwargs)
    elapsed_time = time.time() - start
    if elapsed_time < 60:
      print(f'Executed time: {elapsed_time:.2f} secs')
    else:
      print(f'Executed time: {elapsed_time / 60:.2f} mins')
    return result
  return wrapper
```

**Comment by GCBallesteros** [comment]
You are not using ipython here but just python. By that I mean the repl that opens when you run the `python` program without arguments on your terminal. It's is a bit more picky about the indentation than ipython. My recommendations would be to use ipython instead it's much better in every way. For that:
1. Make sure to have iron configured to use ipython
2. Have ipython installed on the venv you have active before starting nvim

**Comment by tabrez** [comment]
You're right, I'm getting the exact same error when copy/pasting the code inside a `python` repl in the terminal. For some reason, `iron.nvim` is loading either `python` or `ipython` repl arbitrarily on different `nvim` invocations and there are no errors when it loads `ipython` repl. I'm also getting nice syntax colouring in the repl window when `ipython` is loaded. 

I'm getting the `ipython` every single time if I make the following change to the `iron.nvim` config:

```lua
config = {
  repl_open_cmd = require('iron.view').split.vertical.botright("50%"),
  repl_definition = { python = require("iron.fts.python").ipython },
}
```

Thanks for the help, you can close this issue.

**Comment by GCBallesteros** [comment]
No problem. Enjoy!
