### ISSUE TITLE
First time you call the hydra you end up in insert mode

### ISSUE THREAD

**Issue by raffaem** [GCBallesteros/NotebookNavigator.nvim#33]
The first time you run a cell with the hydra, i.e. `<space>hx`, the cell is send over to the REPL correctly, the cursor is moved down to next cell correctly, but you are left in insert mode for some reason

**Comment by raffaem** [comment]
I think this is an iron.nvim bug, as it happens also without calling NotebookNavigator functionalities: https://github.com/Vigemus/iron.nvim/issues/207

**Comment by raffaem** [comment]
iron.nvim seems half-abandoned. Can we work around this bug by issuing `<Esc>` after hydra commands?

**Comment by GCBallesteros** [comment]
I'm afraid I can't reproduce this. I stay in normal mode after following the sequence of steps you describe above. I'm on 0.10.0 while I test this but I believe that last time I tried on the latest 0.9.* everything was fine too.
