### ISSUE TITLE
`swap_cell` should swap cell separators too

### ISSUE THREAD

**Issue by raffaem** [GCBallesteros/NotebookNavigator.nvim#34]
`swap_cell('u')` swaps the _content_ of the current cell with the cell above.

A new cell separator is created for the current cell (why?), while the cell above retains the old cell separators.

Since I have comments in my cell separator (e.g. `# %% This cell calculate the derivative`), I would like the cell separators to be swapped as well.

**Comment by GCBallesteros** [comment]
It's definitely a good idea for swap cells to move also the cell separator. I will look into it.

As to why. Well, the honest answer is simply that it was the easiest thing to implement and didn't though about the ramifications for additional information/comments on the cell separator line.

**Comment by raffaem** [comment]
> It's definitely a good idea for swap cells to move also the cell separator. I will look into it.
> 
> As to why. Well, the honest answer is simply that it was the easiest thing to implement and didn't though about the ramifications for additional information/comments on the cell separator line.

Thanks!

**Comment by GCBallesteros** [comment]
Hi @raffaem I finally got around to implementing this on #46. It has now be pushed to main.

Cheers

**Comment by raffaelemancuso** [comment]
Yes it works now.

Thanks!
