### ISSUE TITLE
`run_cell` with toggleterm backend does not send indentation lines over

### ISSUE THREAD

**Issue by raffaem** [GCBallesteros/NotebookNavigator.nvim#35]
The `run_cell` function with the toggleterm backend does not send indentation line over.

Here is a screencap.

The first time I use NotebookNavigator to send the cell to the REPL.

The second time I use toggleterm directly.

[20240226T121036.webm](https://github.com/GCBallesteros/NotebookNavigator.nvim/assets/54762742/4b24d385-0ee2-42a4-927d-cbfd6b15242c)

**Comment by raffaem** [comment]
Looks like the responsible is here: https://github.com/GCBallesteros/NotebookNavigator.nvim/blob/main/lua/notebook-navigator/repls.lua#L18?

@GCBallesteros why this line? Can I send a PR that removes it?

**Comment by jonboh** [comment]
yeah, changing that line fixes the issue, although newlines break cells so they have to be filtered out, and ipython has to be run with `ipython --no-autoindent`

**Comment by GCBallesteros** [comment]
@raffaem Was this fixed by your recent PR #40?

**Comment by raffaelemancuso** [comment]
> @raffaem Was this fixed by your recent PR #40?

Looks like so
