### ISSUE TITLE
Providing an alternate repl provider

### ISSUE THREAD

**Issue by IndianBoy42** [GCBallesteros/NotebookNavigator.nvim#43]
I would like to use this with my own plugin for interacting with kitty terminals to use as the reply. Would it be possible to allow passing some kind of object to the `repl_provider` config option so that the user could provide their own repl. I would be happy to upstream the integration once I am more happy with the kitty terminal plugin to release it to the public.

**Comment by GCBallesteros** [comment]
Hi @IndianBoy42 ,

Thanks for taking the time to take a look at NotebookNavigator. I'll be happy to accept a PR that integrates your plugin into NotebookNavigator in the future. However, at the moment I don't have the bandwidth to implement this feature.
