### ISSUE TITLE
Add additional cell operations

### ISSUE THREAD

**Issue by cnrrobertson** [GCBallesteros/NotebookNavigator.nvim#6]
A few that I think are useful:

1. Merge cell (either with above or below)
3. Split cell at cursor
4. Convert cell to code or markdown (just by appending or removing label - makes it easier to export to an actual notebook via jupytext)
5. Delete cell (can already do with operator textobject but could be nice to have in Hydra menu)
6. Duplicate cell
7. Run all cells (or run entire file) / run all cells above or below
8. Swap cell with above or below

I've implemented most of these in [my own plugin](https://github.com/cnrrobertson/nvim-repl-cells/tree/main) that I've been using for some time, but I really like how you've approached the "code cell" functionality in neovim. I'd be happy to implement them here in your style.

**Comment by GCBallesteros** [comment]
New feaetures have been merged into main
