### ISSUE TITLE
Highlighting cell marker lines

### ISSUE THREAD

**Issue by cnrrobertson** [GCBallesteros/NotebookNavigator.nvim#8]
It can be nice to get a visual distinction between cells, i.e. some line highlighting. This is a nice feature I saw in [vim-jukit](https://github.com/luk400/vim-jukit).

I have a basic implementation for this highlighting [here](https://github.com/cnrrobertson/nvim-repl-cells/blob/main/lua/nvim-repl-cells/cells.lua#L289-L308) with autocmds to adjust the highlighting [here](https://github.com/cnrrobertson/nvim-repl-cells/blob/main/lua/nvim-repl-cells.lua#L36)

**Comment by GCBallesteros** [comment]
I highlight cell markers on my own config but my solution is much less refined. Just a regex for `# %%`.

This is definitely something that could also be added. PRs welcome as usual!

P.S. I've seen you've put a few other good issues #7 and #6, and gracefully offered  to implement them. I don't want to abuse too much of your time so maybe we could split the work?

**Comment by cnrrobertson** [comment]
Okay great! I'll put in a PR.

As far as the other issues go, they should honestly be quick for me building off my previous implementations.
